import { photoshop } from "../globals";
const { action } = photoshop;
const { batchPlay } = action;
const { app } = photoshop;









async function getUserGeneratedSlices(doc) {
  try {
    const docResult = await batchPlay([
      {
        _obj: "get",
        _target: [
          { _property: "slices" },
          {
            _ref: "document",
            _enum: "ordinal",
            _value: "targetEnum"
          }
        ]
      }
    ], {});

    const result = docResult[0];

    if (!result.slices || !result.slices.slices) {
      console.log("No slices found in document");
      return [];
    }

    const allSlices = result.slices.slices;
    const nonAutoSlices = [];

    for (let i = 0; i < allSlices.length; i++) {
      const slice = allSlices[i];
      let isAutoGenerated = false;

      if (slice.origin) {
        if (typeof slice.origin === 'string' && slice.origin === 'autoGenerated') {
          isAutoGenerated = true;
        } else if (slice.origin._value && slice.origin._value === 'autoGenerated') {
          isAutoGenerated = true;
        }
      }

      if (!isAutoGenerated) {
        const sliceObject = {
          id: slice.sliceID,
          name: slice.name || `Slice ${i + 1}`,
          bounds:  { top: slice.bounds.top, left: slice.bounds.left, bottom: slice.bounds.bottom, right: slice.bounds.right },
          dimensions: {
            width: (slice.bounds ? slice.bounds.right - slice.bounds.left : 0),
            height: (slice.bounds ? slice.bounds.bottom - slice.bounds.top : 0)
          }
        };

        nonAutoSlices.push(sliceObject);
      }
    }
    // console.log(`Total USER slices found: ${nonAutoSlices.length}`);
    return nonAutoSlices;

  } catch (error) {
    console.error("Error getting non-auto-generated slices:", error);
    return [];
  }
}


function findSliceForLayer(layer, userSlices, threshold = 0.2) {
  const layerBounds = layer.bounds;
  const layerArea = (layerBounds.right - layerBounds.left) * (layerBounds.bottom - layerBounds.top);
  if (layerArea === 0) return null;

  return userSlices.find(slice => {
    const sliceBounds = slice.bounds;
    const overlapX = Math.min(layerBounds.right, sliceBounds.right) - Math.max(layerBounds.left, sliceBounds.left);
    const overlapY = Math.min(layerBounds.bottom, sliceBounds.bottom) - Math.max(layerBounds.top, sliceBounds.top);
    if (overlapX <= 0 || overlapY <= 0) return false;
    return (overlapX * overlapY) / layerArea >= threshold;
  });
}


async function findMySlice(layer) {
  const doc = app.activeDocument;
  const userSlices = await getUserGeneratedSlices(doc);
  const containingSlice = findSliceForLayer(layer, userSlices);
  if (containingSlice) {
    // console.log(`Layer "${layer.name}" is contained in slice:`, containingSlice);
    return containingSlice;
  } else {
    console.log(`Cant find a slice containing the active layer "${layer.name}"`);
  }
}


async function centerLayerToBounds(layer, targetBounds, axis) {
    const b = layer.bounds;

    const layerCenterX = (b.left + b.right) / 2;
    const layerCenterY = (b.top + b.bottom) / 2;
    const targetCenterX = (targetBounds.left + targetBounds.right) / 2;
    const targetCenterY = (targetBounds.top + targetBounds.bottom) / 2;
    if (axis === "x") {
      await layer.translate(targetCenterX - layerCenterX, 0);
    }else if (axis === "y") {
      await layer.translate(0, targetCenterY - layerCenterY);
    }else{
      await layer.translate(targetCenterX - layerCenterX, targetCenterY - layerCenterY);
    }
}


export async function centerLayerToSlice(axis) {
  const doc = app.activeDocument;
  const activeLayer = doc.activeLayers[0];
  const slice = await findMySlice(activeLayer);
  const sliceBounds = slice.bounds;
  console.log("Slice bounds:", sliceBounds);
  await centerLayerToBounds(activeLayer, sliceBounds, axis);
}


function getAllBounds(layer) {
  function pick(boundDimensions) {
    if (!boundDimensions) return null;
    const width = boundDimensions.width?._value ?? boundDimensions.width;
    const height = boundDimensions.height?._value ?? boundDimensions.height;
    if (typeof width === 'number' && typeof height === 'number') {
      return { width: width, height: height };
    }
    return null;
  }

  return {
    bounds: pick(layer.bounds),
    boundsNoMask: pick(layer.boundsNoMask),
    boundsNoEffects: pick(layer.boundsNoEffects),
    boundingBox: pick(layer.boundingBox),
  };
}


function calculateScaleDifference(dimensions1, dimensions2) {
  const widthDifference = ((dimensions2.width - dimensions1.width) / dimensions1.width) * 100;
  const heightDifference = ((dimensions2.height - dimensions1.height) / dimensions1.height) * 100;
  return { widthDifference, heightDifference };
}


async function hasActiveEffects(layerID) {
  const res = await batchPlay([{
    _obj: "get",
    _target: [{ _ref: "layer", _id: layerID }]
  }], {});

  const effects = res[0]?.layerEffects;
  if (!effects) return false;

  for (const key in effects) {
    if (key === "scale") continue;
    const val = effects[key];
    if (Array.isArray(val) ? val.some(e => e.enabled) : val?.enabled) return true;
  }
  return false;
}



export async function scaleDownToSlice(layer) {
  const sliceInfo = await findMySlice(layer);
  const sliceDimensions = sliceInfo?.dimensions;
  if (!sliceDimensions) { app.showAlert("No slice found"); return; }

  const layerBounds = getAllBounds(layer);
  const layerDimensions = layerBounds.bounds;
  if (!layerDimensions) { console.log("Cannot read layer transparency"); return; }

  // console.log("── scaleDownToSlice ──");
  // console.log("Layer bounds BEFORE:", JSON.stringify(layerDimensions));
  // console.log("Layer boundsNoEffects:", JSON.stringify(layerBounds.boundsNoEffects));

  // console.log("Slice dimensions:", JSON.stringify(sliceDimensions));

  const difference = calculateScaleDifference(layerDimensions, sliceDimensions);
  // console.log("Scale differences (percent):", difference);
  const scalePercent = (100 + Math.min(difference.widthDifference, difference.heightDifference)) * 0.90;
  // console.log("Calculated scale percent:", scalePercent);
  if (scalePercent >= 90 && scalePercent <= 102) return;

  await batchPlay([{
    _obj: "transform",
    freeTransformCenterState: { _enum: "quadCenterState", _value: "QCSAverage" },
    width: { _unit: "percentUnit", _value: scalePercent },
    height: { _unit: "percentUnit", _value: scalePercent },
    _options: { dialogOptions: "dontDisplay" }
  }], {});
  const boundsAfter = layer.bounds;
  // console.log("Layer bounds AFTER transform:", JSON.stringify({
  //   width: boundsAfter.right - boundsAfter.left,
  //   height: boundsAfter.bottom - boundsAfter.top
  // }));
  const hasFX = await hasActiveEffects(layer.id);
  if (hasFX && Number.isNaN(scalePercent) === false) {
  await batchPlay([{
    _obj: "scaleEffectsEvent",
    scale: { _unit: "percentUnit", _value: scalePercent },
    _options: { dialogOptions: "dontDisplay" }
  }], {});}

  await centerLayerToBounds(layer, sliceInfo.bounds, "x");
}



